networks:
  inception:
    name: inception

services:
  # nginx:
  #   build: ./requirements/nginx/.
  #   container_name: nginx
  #   ports:
  #       - "443:443"
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - ./web:/var/www/html
  #   networks:
  #     - inception
  #   restart: always
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always