volumes:
  # wordpress:
    # name: wordpress
    # driver: local
    # driver_opts:
    #   device: ${PWD}/srcs/requirements/wordpress
    #   o: bind 
    #   type: none   
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ${PWD}/srcs/requirements/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  # nginx:
  #   build: ./requirements/nginx/.
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #     - inception
  #   restart: always
  # wordpress:
  #   build: ./requirements/wordpress/.
  #   container_name: wordpress
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress:/var/www/html
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   restart: always
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always