volumes:
  wordpress:
    driver: local  
  mariadb:
    driver: local

networks:
  inception:
    name: inception

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
        - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    build: 
        args:
          - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_USER_EMAIL=${MYSQL_USER_EMAIL}
          - MYSQL_HOST=${MYSQL_HOST}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - DATABASE_NAME=${DATABASE_NAME}
        context: ./requirements/mariadb/.
        dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always