networks:
  inception:
    name: inception

services:
  nginx:
    build:
      context: ..
      dockerfile: srcs/requirements/nginx/Dockerfile
    container_name: nginx
    ports:
        - "443:443"
    depends_on:
      - wordpress
    volumes:
      - webdata:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build:
      context: ..
      dockerfile: srcs/requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - webdata:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    build:
      context: ..
      dockerfile: srcs/requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
volumes:
  webdata:
    driver: local